### ISSUE TITLE
Doesn't export 

### ISSUE THREAD

**Issue by GuusDeKroon** [mukaderabbit/mukaderabbit-HyakuashiUdonMotionRecorder-HUMR-#1]
Hello, I recently purchased HUMR, but none of the recorded animations can be exported to a .fbx file.
I don't see any errors, but when I click the button nothing happens.
Everything looks good in the output_log file, but nothing happens when click the export button.

**Comment by mukaderabbit** [comment]
I communicated with the other contact.
The "DisplayName" was not entered correctly.
Resolved.
